// {
//     "products": [
//       {
//         "id": "1",
//         "name": "Armchair Tortuga",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (19).png",
//         "price": 85,
//         "description": "An elegant armchair with plush cushions and a curved design for comfort.",
//         "discountPercentage": 23,
//         "isFeaturedProduct": false,
//         "stockLevel": 23,
//         "category": "Chair",
//         "tags": ["trendingProduct"],
//         "brand": "Fusion Dot High Fashion",
//         "rating": 3
//       },
//       {
//         "id": "2",
//         "name": "Tribù Elio Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (13).png",
//         "price": 120,
//         "description": "A sleek outdoor chair with natural wooden elements and a modern look.",
//         "discountPercentage": 23,
//         "isFeaturedProduct": true,
//         "stockLevel": 17,
//         "category": "Chair",
//         "tags": ["trendingProduct"],
//         "brand": "Coaster Furniture",
//         "rating": 4
//       },
//       {
//         "id": "3",
//         "name": "Uchiwa Quilted Lounge Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (6).png",
//         "price": 160,
//         "description": "A spacious lounge chair with a quilted back and soft cushioning.",
//         "discountPercentage": 20,
//         "isFeaturedProduct": true,
//         "stockLevel": 5,
//         "category": "Chair",
//         "tags": ["trendingProduct"],
//         "brand": "Unique Furniture Restor",
//         "rating": 5
//       },
//       {
//         "id": "4",
//         "name": "Stylish Golden Metal Legs Mint Blue Fabric Velvet Sofa Leisure Armchair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (3).png",
//         "price": 78,
//         "description": "A luxurious armchair with velvet fabric and golden metal legs.",
//         "discountPercentage": 0,
//         "isFeaturedProduct": false,
//         "stockLevel": 12,
//         "category": "Sofa",
//         "tags": ["topCategory"],
//         "brand": "Dream Furniture Flipping",
//         "rating": 2
//       },
//       {
//         "id": "5",
//         "name": "Hans Wegner Style Three-Legged Shell Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (4).png",
//         "price": 99,
//         "description": "Iconic three-legged chair with faux leather and ash plywood frame.",
//         "discountPercentage": 10,
//         "isFeaturedProduct": false,
//         "stockLevel": 8,
//         "category": "Chair",
//         "tags": ["newArrival", "bestSeller"],
//         "brand": "Dream Furniture Flipping",
//         "rating": 1
//       },
//       {
//         "id": "6",
//         "name": "Rapson Thirty-Nine Guest Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (7).png",
//         "price": 130,
//         "description": "A mid-century modern chair with clean lines and durable materials.",
//         "discountPercentage": 15,
//         "isFeaturedProduct": true,
//         "stockLevel": 20,
//         "category": "Chair",
//         "tags": ["specialOffer"],
//         "brand": "Green DIY furniture",
//         "rating": 4
//       },
//       {
//         "id": "7",
//         "name": "Nautilus Lounge Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (8).png",
//         "price": 145,
//         "description": "A lounge chair with a shell-inspired design and premium upholstery.",
//         "discountPercentage": 12,
//         "isFeaturedProduct": true,
//         "stockLevel": 10,
//         "category": "Chair",
//         "tags": ["bestSeller"],
//         "brand": "Coaster Furniture",
//         "rating": 3
//       },
//       {
//         "id": "8",
//         "name": "High Quality Modern Customized Plastic Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (9).png",
//         "price": 15,
//         "description": "A simple and lightweight chair ideal for dining or casual use.",
//         "discountPercentage": 0,
//         "isFeaturedProduct": false,
//         "stockLevel": 50,
//         "category": "Chair",
//         "tags": ["trendingProduct"],
//         "brand": "Fusion Dot High Fashion",
//         "rating": 5
//       },
//       {
//         "id": "9",
//         "name": "Cozy Armchair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (10).png",
//         "price": 52,
//         "description": "Compact armchair with a cozy design for small spaces.",
//         "discountPercentage": 8,
//         "isFeaturedProduct": false,
//         "stockLevel": 15,
//         "category": "Chair",
//         "tags": ["topCategory"],
//         "brand": "Unique Furniture Restor",
//         "rating": 2
//       },
//       {
//         "id": "10",
//         "name": "Alpha Chair – Solid Ebonised Oak",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (11).png",
//         "price": 9,
//         "description": "A sturdy oak chair with a sleek and minimalist design.",
//         "discountPercentage": 10,
//         "isFeaturedProduct": false,
//         "stockLevel": 18,
//         "category": "Chair",
//         "tags": ["newArrival"],
//         "brand": "Dream Furniture Flipping",
//         "rating": 1
//       },
//       {
//         "id": "11",
//         "name": "Replica Hans Wegner Wishbone Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (12).png",
//         "price": 75,
//         "description": "Classic wishbone chair with a dark walnut frame and cord seat.",
//         "discountPercentage": 10,
//         "isFeaturedProduct": false,
//         "stockLevel": 25,
//         "category": "Chair",
//         "tags": ["bestSeller", "specialOffer"],
//         "brand": "Young Repurposed",
//         "rating": 4
//       },
//       {
//         "id": "12",
//         "name": "Futuristic Sleek Modern Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (14).png",
//         "price": 200,
//         "description": "A modern chair with a carbon fiber frame and bold red accents.",
//         "discountPercentage": 0,
//         "isFeaturedProduct": true,
//         "stockLevel": 3,
//         "category": "Chair",
//         "tags": ["trendingProduct"],
//         "brand": "Young Repurposed",
//         "rating": 5
//       },
//       {
//         "id": "13",
//         "name": "Liberty Wood 63' Floating Entertainment Center",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (15).png",
//         "price": 110,
//         "description": "Versatile entertainment chair for modern interiors.",
//         "discountPercentage": 8,
//         "isFeaturedProduct": false,
//         "stockLevel": 7,
//         "category": "Chair",
//         "tags": ["newArrival"],
//         "brand": "Green DIY furniture",
//         "rating": 3
//       },
//       {
//         "id": "14",
//         "name": "Leisure Sofa Chair Set",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (16).png",
//         "price": 180,
//         "description": "A comfortable set of chairs with soft cushions for relaxation.",
//         "discountPercentage": 18,
//         "isFeaturedProduct": true,
//         "stockLevel": 6,
//         "category": "Sofa",
//         "tags": ["bestSeller"],
//         "brand": "Dream Furniture Flipping",
//         "rating": 4
//       },
//       {
//         "id": "15",
//         "name": "Diondre Chair - Tuft Button - Acrylic Legs",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (17).png",
//         "price": 72,
//         "description": "A tufted chair with acrylic legs for a chic, modern touch.",
//         "discountPercentage": 7,
//         "isFeaturedProduct": false,
//         "stockLevel": 10,
//         "category": "Chair",
//         "tags": ["specialOffer"],
//         "brand": "Coaster Furniture",
//         "rating": 2
//       },
//       {
//         "id": "16",
//         "name": "Matilda Velvet Chair – Pink",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (18).png",
//         "price": 60,
//         "description": "A vibrant pink velvet chair with a retro-inspired design.",
//         "discountPercentage": 15,
//         "isFeaturedProduct": true,
//         "stockLevel": 12,
//         "category": "Chair",
//         "tags": ["newArrival"],
//         "brand": "Dream Furniture Flipping",
//         "rating": 5
//       },
//       {
//         "id": "17",
//         "name": "Varmora Plastic Chair Solid",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (19).png",
//         "price": 10,
//         "description": "Durable and lightweight plastic chair for everyday use.",
//         "discountPercentage": 25,
//         "isFeaturedProduct": false,
//         "stockLevel": 100,
//         "category": "Chair",
//         "tags": ["topCategory"],
//         "brand": "Unique Furniture Restor",
//         "rating": 1
//       },
//       {
//         "id": "18",
//         "name": "Sobuy Blue Folding Chair Wooden Padded",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (21).png",
//         "price": 12,
//         "description": "A foldable wooden chair with a padded seat for extra comfort.",
//         "discountPercentage": 12,
//         "isFeaturedProduct": false,
//         "stockLevel": 30,
//         "category": "Chair",
//         "tags": ["bestSeller"],
//         "brand": "Young Repurposed",
//         "rating": 3
//       },
//       {
//         "id": "19",
//         "name": "Nordic Net Red Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (22).png",
//         "price": 32,
//         "description": "An acrylic dining chair with a sleek and minimalist Nordic design.",
//         "discountPercentage": 10,
//         "isFeaturedProduct": true,
//         "stockLevel": 20,
//         "category": "Chair",
//         "tags": ["trendingProduct"],
//         "brand": "Green DIY furniture",
//         "rating": 4
//       },
//       {
//         "id": "20",
//         "name": "Cantilever Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (23).png",
//         "price": 78,
//         "description": "A modern cantilever chair with a unique floating effect.",
//         "discountPercentage": 15,
//         "isFeaturedProduct": true,
//         "stockLevel": 5,
//         "category": "Chair",
//         "tags": ["specialOffer"],
//         "brand": "Coaster Furniture",
//         "rating": 2
//       },
//       {
//         "id": "21",
//         "name": "Luxury Flower Shell Sofa Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (34).png",
//         "price": 250,
//         "description": "A luxurious shell-shaped chair with gold brass metal legs.",
//         "discountPercentage": 0,
//         "isFeaturedProduct": true,
//         "stockLevel": 2,
//         "category": "Sofa",
//         "tags": ["newArrival"],
//         "brand": "Fusion Dot High Fashion",
//         "rating": 5
//       },
//       {
//         "id": "22",
//         "name": "Tribù Elio Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (5).png",
//         "price": 120,
//         "description": "A sleek outdoor chair with natural wooden elements and a modern look.",
//         "discountPercentage": 10,
//         "isFeaturedProduct": true,
//         "stockLevel": 25,
//         "category": "Chair",
//         "tags": ["specialOffer"],
//         "brand": "Coaster Furniture",
//         "rating": 4
//       },
//       {
//         "id": "23",
//         "name": "Armchair Tortuga",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (35).png",
//         "price": 85,
//         "description": "An elegant armchair with plush cushions and a curved design for comfort.",
//         "discountPercentage": 0,
//         "isFeaturedProduct": false,
//         "stockLevel": 10,
//         "category": "Chair",
//         "tags": ["specialOffer", "topCategory"],
//         "brand": "Fusion Dot High Fashion",
//         "rating": 3
//       },
//       {
//         "id": "24",
//         "name": "Uchiwa Quilted Lounge Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (6).png",
//         "price": 160,
//         "description": "A spacious lounge chair with a quilted back and soft cushioning.",
//         "discountPercentage": 20,
//         "isFeaturedProduct": true,
//         "stockLevel": 5,
//         "category": "Chair",
//         "tags": ["trendingProduct"],
//         "brand": "Unique Furniture Restor",
//         "rating": 5
//       },
//       {
//         "id": "25",
//         "name": "Stylish Golden Metal Legs Mint Blue Fabric Velvet Sofa Leisure Armchair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (3).png",
//         "price": 78,
//         "description": "A luxurious armchair with velvet fabric and golden metal legs.",
//         "discountPercentage": 0,
//         "isFeaturedProduct": false,
//         "stockLevel": 12,
//         "category": "Sofa",
//         "tags": ["topCategory"],
//         "brand": "Dream Furniture Flipping",
//         "rating": 2
//       },
//       {
//         "id": "26",
//         "name": "Hans Wegner Style Three-Legged Shell Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (4).png",
//         "price": 99,
//         "description": "Iconic three-legged chair with faux leather and ash plywood frame.",
//         "discountPercentage": 10,
//         "isFeaturedProduct": false,
//         "stockLevel": 8,
//         "category": "Chair",
//         "tags": ["newArrival", "bestSeller"],
//         "brand": "Dream Furniture Flipping",
//         "rating": 1
//       },
//       {
//         "id": "27",
//         "name": "Rapson Thirty-Nine Guest Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (7).png",
//         "price": 130,
//         "description": "A mid-century modern chair with clean lines and durable materials.",
//         "discountPercentage": 15,
//         "isFeaturedProduct": true,
//         "stockLevel": 20,
//         "category": "Chair",
//         "tags": ["specialOffer"],
//         "brand": "Green DIY furniture",
//         "rating": 4
//       },
//       {
//         "id": "28",
//         "name": "Nautilus Lounge Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (8).png",
//         "price": 145,
//         "description": "A lounge chair with a shell-inspired design and premium upholstery.",
//         "discountPercentage": 12,
//         "isFeaturedProduct": true,
//         "stockLevel": 10,
//         "category": "Chair",
//         "tags": ["bestSeller"],
//         "brand": "Coaster Furniture",
//         "rating": 3
//       },
//       {
//         "id": "29",
//         "name": "High Quality Modern Customized Plastic Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (9).png",
//         "price": 15,
//         "description": "A simple and lightweight chair ideal for dining or casual use.",
//         "discountPercentage": 0,
//         "isFeaturedProduct": false,
//         "stockLevel": 50,
//         "category": "Chair",
//         "tags": ["trendingProduct"],
//         "brand": "Fusion Dot High Fashion",
//         "rating": 5
//       },
//       {
//         "id": "30",
//         "name": "Cozy Armchair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (10).png",
//         "price": 52,
//         "description": "Compact armchair with a cozy design for small spaces.",
//         "discountPercentage": 8,
//         "isFeaturedProduct": false,
//         "stockLevel": 15,
//         "category": "Chair",
//         "tags": ["topCategory"],
//         "brand": "Unique Furniture Restor",
//         "rating": 2
//       },
//       {
//         "id": "31",
//         "name": "Alpha Chair – Solid Ebonised Oak",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (11).png",
//         "price": 90,
//         "description": "A sturdy oak chair with a sleek and minimalist design.",
//         "discountPercentage": 10,
//         "isFeaturedProduct": false,
//         "stockLevel": 18,
//         "category": "Chair",
//         "tags": ["newArrival"],
//         "brand": "Dream Furniture Flipping",
//         "rating": 1
//       },
//       {
//         "id": "32",
//         "name": "Replica Hans Wegner Wishbone Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (12).png",
//         "price": 75,
//         "description": "Classic wishbone chair with a dark walnut frame and cord seat.",
//         "discountPercentage": 10,
//         "isFeaturedProduct": false,
//         "stockLevel": 25,
//         "category": "Chair",
//         "tags": ["bestSeller", "specialOffer"],
//         "brand": "Young Repurposed",
//         "rating": 4
//       },
//       {
//         "id": "33",
//         "name": "Futuristic Sleek Modern Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (14).png",
//         "price": 200,
//         "description": "A modern chair with a carbon fiber frame and bold red accents.",
//         "discountPercentage": 0,
//         "isFeaturedProduct": true,
//         "stockLevel": 3,
//         "category": "Chair",
//         "tags": ["trendingProduct"],
//         "brand": "Young Repurposed",
//         "rating": 5
//       },
//       {
//         "id": "34",
//         "name": "Liberty Wood 63' Floating Entertainment Center",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (15).png",
//         "price": 110,
//         "description": "Versatile entertainment chair for modern interiors.",
//         "discountPercentage": 8,
//         "isFeaturedProduct": false,
//         "stockLevel": 7,
//         "category": "Chair",
//         "tags": ["newArrival"],
//         "brand": "Green DIY furniture",
//         "rating": 3
//       },
//       {
//         "id": "35",
//         "name": "Leisure Sofa Chair Set",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (16).png",
//         "price": 180,
//         "description": "A comfortable set of chairs with soft cushions for relaxation.",
//         "discountPercentage": 18,
//         "isFeaturedProduct": true,
//         "stockLevel": 6,
//         "category": "Sofa",
//         "tags": ["bestSeller"],
//         "brand": "Dream Furniture Flipping",
//         "rating": 4
//       },
//       {
//         "id": "36",
//         "name": "Diondre Chair - Tuft Button - Acrylic Legs",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (17).png",
//         "price": 72,
//         "description": "A tufted chair with acrylic legs for a chic, modern touch.",
//         "discountPercentage": 7,
//         "isFeaturedProduct": false,
//         "stockLevel": 10,
//         "category": "Chair",
//         "tags": ["specialOffer"],
//         "brand": "Coaster Furniture",
//         "rating": 2
//       },
//       {
//         "id": "37",
//         "name": "Matilda Velvet Chair – Pink",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (18).png",
//         "price": 60,
//         "description": "A vibrant pink velvet chair with a retro-inspired design.",
//         "discountPercentage": 15,
//         "isFeaturedProduct": true,
//         "stockLevel": 12,
//         "category": "Chair",
//         "tags": ["newArrival"],
//         "brand": "Dream Furniture Flipping",
//         "rating": 5
//       },
//       {
//         "id": "38",
//         "name": "Varmora Plastic Chair Solid",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (19).png",
//         "price": 10,
//         "description": "Durable and lightweight plastic chair for everyday use.",
//         "discountPercentage": 25,
//         "isFeaturedProduct": false,
//         "stockLevel": 100,
//         "category": "Chair",
//         "tags": ["topCategory"],
//         "brand": "Unique Furniture Restor",
//         "rating": 1
//       },
//       {
//         "id": "39",
//         "name": "Sobuy Blue Folding Chair Wooden Padded",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (21).png",
//         "price": 12,
//         "description": "A foldable wooden chair with a padded seat for extra comfort.",
//         "discountPercentage": 12,
//         "isFeaturedProduct": false,
//         "stockLevel": 30,
//         "category": "Chair",
//         "tags": ["bestSeller"],
//         "brand": "Young Repurposed",
//         "rating": 3
//       },
//       {
//         "id": "40",
//         "name": "Nordic Net Red Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (22).png",
//         "price": 32,
//         "description": "An acrylic dining chair with a sleek and minimalist Nordic design.",
//         "discountPercentage": 10,
//         "isFeaturedProduct": true,
//         "stockLevel": 20,
//         "category": "Chair",
//         "tags": ["trendingProduct"],
//         "brand": "Green DIY furniture",
//         "rating": 4
//       },
//       {
//         "id": "41",
//         "name": "Cantilever Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (23).png",
//         "price": 78,
//         "description": "A modern cantilever chair with a unique floating effect.",
//         "discountPercentage": 15,
//         "isFeaturedProduct": true,
//         "stockLevel": 5,
//         "category": "Chair",
//         "tags": ["specialOffer"],
//         "brand": "Coaster Furniture",
//         "rating": 2
//       },
//       {
//         "id": "42",
//         "name": "Luxury Flower Shell Sofa Chair",
//         "imagePath": "https://media.istockphoto.com/id/144293437/photo/wooden-chair.jpg?s=612x612&w=0&k=20&c=edjQRvQj8iiXFSW8POirO3z0MImbeXyzPBm69DRms4w=",
//         "price": 250,
//         "description": "A luxurious shell-shaped chair with gold brass metal legs.",
//         "discountPercentage": 0,
//         "isFeaturedProduct": true,
//         "stockLevel": 2,
//         "category": "Sofa",
//         "tags": ["newArrival"],
//         "brand": "Fusion Dot High Fashion",
//         "rating": 5
//       },
//       {
//         "id": "43",
//         "name": "Tribù Elio Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (5).png",
//         "price": 120,
//         "description": "A sleek outdoor chair with natural wooden elements and a modern look.",
//         "discountPercentage": 10,
//         "isFeaturedProduct": true,
//         "stockLevel": 25,
//         "category": "Chair",
//         "tags": ["specialOffer"],
//         "brand": "Coaster Furniture",
//         "rating": 4
//       },
//       {
//         "id": "44",
//         "name": "Armchair Tortuga",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (35).png",
//         "price": 85,
//         "description": "An elegant armchair with plush cushions and a curved design for comfort.",
//         "discountPercentage": 0,
//         "isFeaturedProduct": false,
//         "stockLevel": 10,
//         "category": "Chair",
//         "tags": ["specialOffer", "topCategory"],
//         "brand": "Fusion Dot High Fashion",
//         "rating": 3
//       },
//       {
//         "id": "45",
//         "name": "Uchiwa Quilted Lounge Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (6).png",
//         "price": 160,
//         "description": "A spacious lounge chair with a quilted back and soft cushioning.",
//         "discountPercentage": 20,
//         "isFeaturedProduct": true,
//         "stockLevel": 5,
//         "category": "Chair",
//         "tags": ["trendingProduct"],
//         "brand": "Unique Furniture Restor",
//         "rating": 5
//       },
//       {
//         "id": "46",
//         "name": "Stylish Golden Metal Legs Mint Blue Fabric Velvet Sofa Leisure Armchair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (3).png",
//         "price": 78,
//         "description": "A luxurious armchair with velvet fabric and golden metal legs.",
//         "discountPercentage": 0,
//         "isFeaturedProduct": false,
//         "stockLevel": 12,
//         "category": "Sofa",
//         "tags": ["topCategory"],
//         "brand": "Dream Furniture Flipping",
//         "rating": 2
//       },
//       {
//         "id": "47",
//         "name": "Hans Wegner Style Three-Legged Shell Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (4).png",
//         "price": 99,
//         "description": "Iconic three-legged chair with faux leather and ash plywood frame.",
//         "discountPercentage": 10,
//         "isFeaturedProduct": false,
//         "stockLevel": 8,
//         "category": "Chair",
//         "tags": ["newArrival", "bestSeller"],
//         "brand": "Dream Furniture Flipping",
//         "rating": 1
//       },
//       {
//         "id": "48",
//         "name": "Rapson Thirty-Nine Guest Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (7).png",
//         "price": 130,
//         "description": "A mid-century modern chair with clean lines and durable materials.",
//         "discountPercentage": 15,
//         "isFeaturedProduct": true,
//         "stockLevel": 20,
//         "category": "Chair",
//         "tags": ["specialOffer"],
//         "brand": "Green DIY furniture",
//         "rating": 4
//       },
//       {
//         "id": "49",
//         "name": "Nautilus Lounge Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (8).png",
//         "price": 145,
//         "description": "A lounge chair with a shell-inspired design and premium upholstery.",
//         "discountPercentage": 12,
//         "isFeaturedProduct": true,
//         "stockLevel": 10,
//         "category": "Chair",
//         "tags": ["bestSeller"],
//         "brand": "Coaster Furniture",
//         "rating": 3
//       },
//       {
//         "id": "50",
//         "name": "High Quality Modern Customized Plastic Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (9).png",
//         "price": 15,
//         "description": "A simple and lightweight chair ideal for dining or casual use.",
//         "discountPercentage": 0,
//         "isFeaturedProduct": false,
//         "stockLevel": 50,
//         "category": "Chair",
//         "tags": ["trendingProduct"],
//         "brand": "Fusion Dot High Fashion",
//         "rating": 5
//       },
//       {
//         "id": "51",
//         "name": "Cozy Armchair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (10).png",
//         "price": 52,
//         "description": "Compact armchair with a cozy design for small spaces.",
//         "discountPercentage": 8,
//         "isFeaturedProduct": false,
//         "stockLevel": 15,
//         "category": "Chair",
//         "tags": ["topCategory"],
//         "brand": "Unique Furniture Restor",
//         "rating": 2
//       },
//       {
//         "id": "52",
//         "name": "Alpha Chair – Solid Ebonised Oak",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (11).png",
//         "price": 90,
//         "description": "A sturdy oak chair with a sleek and minimalist design.",
//         "discountPercentage": 10,
//         "isFeaturedProduct": false,
//         "stockLevel": 18,
//         "category": "Chair",
//         "tags": ["newArrival"],
//         "brand": "Dream Furniture Flipping",
//         "rating": 1
//       },
//       {
//         "id": "53",
//         "name": "Replica Hans Wegner Wishbone Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (12).png",
//         "price": 75,
//         "description": "Classic wishbone chair with a dark walnut frame and cord seat.",
//         "discountPercentage": 10,
//         "isFeaturedProduct": false,
//         "stockLevel": 25,
//         "category": "Chair",
//         "tags": ["bestSeller", "specialOffer"],
//         "brand": "Young Repurposed",
//         "rating": 4
//       },
//       {
//         "id": "54",
//         "name": "Futuristic Sleek Modern Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (14).png",
//         "price": 200,
//         "description": "A modern chair with a carbon fiber frame and bold red accents.",
//         "discountPercentage": 0,
//         "isFeaturedProduct": true,
//         "stockLevel": 3,
//         "category": "Chair",
//         "tags": ["trendingProduct"],
//         "brand": "Young Repurposed",
//         "rating": 5
//       },
//       {
//         "id": "55",
//         "name": "Liberty Wood 63' Floating Entertainment Center",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (15).png",
//         "price": 110,
//         "description": "Versatile entertainment chair for modern interiors.",
//         "discountPercentage": 8,
//         "isFeaturedProduct": false,
//         "stockLevel": 7,
//         "category": "Chair",
//         "tags": ["newArrival"],
//         "brand": "Green DIY furniture",
//         "rating": 3
//       },
//       {
//         "id": "56",
//         "name": "Leisure Sofa Chair Set",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (16).png",
//         "price": 180,
//         "description": "A comfortable set of chairs with soft cushions for relaxation.",
//         "discountPercentage": 18,
//         "isFeaturedProduct": true,
//         "stockLevel": 6,
//         "category": "Sofa",
//         "tags": ["bestSeller"],
//         "brand": "Dream Furniture Flipping",
//         "rating": 4
//       },
//       {
//         "id": "57",
//         "name": "Diondre Chair - Tuft Button - Acrylic Legs",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (17).png",
//         "price": 72,
//         "description": "A tufted chair with acrylic legs for a chic, modern touch.",
//         "discountPercentage": 7,
//         "isFeaturedProduct": false,
//         "stockLevel": 10,
//         "category": "Chair",
//         "tags": ["specialOffer"],
//         "brand": "Coaster Furniture",
//         "rating": 2
//       },
//       {
//         "id": "58",
//         "name": "Matilda Velvet Chair – Pink",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (18).png",
//         "price": 60,
//         "description": "A vibrant pink velvet chair with a retro-inspired design.",
//         "discountPercentage": 15,
//         "isFeaturedProduct": true,
//         "stockLevel": 12,
//         "category": "Chair",
//         "tags": ["newArrival"],
//         "brand": "Dream Furniture Flipping",
//         "rating": 5
//       },
//       {
//         "id": "59",
//         "name": "Varmora Plastic Chair Solid",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (19).png",
//         "price": 10,
//         "description": "Durable and lightweight plastic chair for everyday use.",
//         "discountPercentage": 25,
//         "isFeaturedProduct": false,
//         "stockLevel": 100,
//         "category": "Chair",
//         "tags": ["topCategory"],
//         "brand": "Unique Furniture Restor",
//         "rating": 1
//       },
//       {
//         "id": "60",
//         "name": "Sobuy Blue Folding Chair Wooden Padded",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (21).png",
//         "price": 12,
//         "description": "A foldable wooden chair with a padded seat for extra comfort.",
//         "discountPercentage": 12,
//         "isFeaturedProduct": false,
//         "stockLevel": 30,
//         "category": "Chair",
//         "tags": ["bestSeller"],
//         "brand": "Young Repurposed",
//         "rating": 3
//       },
//       {
//         "id": "61",
//         "name": "Nordic Net Red Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (22).png",
//         "price": 32,
//         "description": "An acrylic dining chair with a sleek and minimalist Nordic design.",
//         "discountPercentage": 10,
//         "isFeaturedProduct": true,
//         "stockLevel": 20,
//         "category": "Chair",
//         "tags": ["trendingProduct"],
//         "brand": "Green DIY furniture",
//         "rating": 4
//       },
//       {
//         "id": "62",
//         "name": "Cantilever Chair",
//         "imagePath": "https://next-ecommerce-template-4.vercel.app/product/Chair (23).png",
//         "price": 78,
//         "description": "A modern cantilever chair with a unique floating effect.",
//         "discountPercentage": 15,
//         "isFeaturedProduct": true,
//         "stockLevel": 5,
//         "category": "Chair",
//         "tags": ["specialOffer"],
//         "brand": "Coaster Furniture",
//         "rating": 2
//       },
//       {
//         "id": "63",
//         "name": "Luxury Flower Shell Sofa Chair",
//         "imagePath": "https://media.istockphoto.com/id/144293437/photo/wooden-chair.jpg?s=612x612&w=0&k=20&c=edjQRvQj8iiXFSW8POirO3z0MImbeXyzPBm69DRms4w=",
//         "price": 250,
//         "description": "A luxurious shell-shaped chair with gold brass metal legs.",
//         "discountPercentage": 0,
//         "isFeaturedProduct": true,
//         "stockLevel": 2,
//         "category": "Sofa",
//         "tags": ["newArrival"],
//         "brand": "Fusion Dot High Fashion",
//         "rating": 5
//       }
//     ]
//   }
  