import type { Metadata } from "next";
import "./globals.css";

import { Josefin_Sans } from "next/font/google";

import Navbar from "@/components/project/Navbar";
import Header from "@/components/project/Header";
import { ClerkProvider } from "@clerk/nextjs";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "@/components/project/Footer";
import ImageAutoSlider from "@/components/project/ImageAutoSlider";
import AddToCartSidebar from "@/components/project/AddToCartSidebar";
import ShoppingCartProvider from "@/components/project/ShoppingCartProvider";

const josefinSans = Josefin_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className={` font-sans ${josefinSans.className}`}>
          <ShoppingCartProvider>
            <AddToCartSidebar />
            <Header />
            <Navbar />
            {children}
            <ImageAutoSlider />
            <Footer />
          </ShoppingCartProvider>
        </body>
      </ClerkProvider>
    </html>
  );
}
